unprotected_forms:
  - user_login_form
  - search_form
  - search_block_form
  - views_exposed_form
  - honeypot_settings_form
protect_all_forms: false
log: false
element_name: url
time_limit: 5
expire: 300
form_settings:
  user_register_form: false
  user_pass: false
  webforms: true
  node_homepage_form: false
  node_page_form: false
  node_partner_form: false
  node_profile_form: false
  node_service_form: false
  comment_comment_form: false
_core:
  default_config_hash: jEhrePho9bAz_8-E-zPMXvlx4knpphzUdaiQJX-xc8Q
