
<?php

/**
 * @file
 * Functions to support theming in the slicklabs_theme theme.
 */


use Drupal\Core\Url;
use Drupal\image\Entity\ImageStyle;

/**
 * Implements hook_theme_suggestions_page_alter().
 */
function slicklabs_theme_theme_suggestions_page_alter(array &$suggestions, array $variables) {
  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    $content_type = $node->bundle();
    $suggestions[] = 'page__node__' . $content_type;
  }
}